CREATE TABLE `b_vkolesnev_formevent` (
        `ID` INT(11) NOT NULL AUTO_INCREMENT,
        `BUTTON_SELECTOR` VARCHAR(65536) NOT NULL,
        `EVENT_NAME` VARCHAR(65536) NOT NULL,
        `FORM_SELECTOR` VARCHAR(65536) NOT NULL,
        `CREATED` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY(ID)
    );